mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls import include,url
from django.conf.urls.static import static


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    # ex: /polls/5/results/
    path('', views.login, name='login'),
    path('student_home/', views.student_home, name='student_home'),
    path('list/',views.list,name='list'),
    path('student_project_detail/', views.student_project_detail, name='student_project_detail'),
    path('student_project_apply/', views.student_project_apply, name='student_project_apply'),
    path('student_project_cancel/', views.student_project_cancel, name='student_project_cancel'),
    path('student_allocated_projects/', views.student_allocated_projects, name='student_allocated_projects'),
    path('student_project_accept/', views.student_project_accept, name='student_project_accept'),
    path('student_project_reject/', views.student_project_reject, name='student_project_reject'),
    path('student_edit_profile/', views.student_edit_profile, name='student_edit_profile'),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('instructor_edit_profile/', views.instructor_edit_profile, name='instructor_edit_profile'),
    path('instructor_update_profile/', views.instructor_update_profile, name='instructor_update_profile'),
    path('student_update_profile/', views.student_update_profile, name='student_update_profile'),
    path('instructor_profile/', views.instructor_profile, name='instructor_profile'),
    path('student_filter_project/', views.student_filter_project, name='student_filter_project'),
    path('search_chat/', views.search_chat, name='search_chat'),

    # path('student_inst_chat/', views.student_inst_chat, name='student_inst_chat'),
    # path('student_new_message/', views.student_new_message, name='student_new_message'),
    path('student_create_chat/', views.student_create_chat, name='student_create_chat'),
    path('student_show_messages/', views.student_show_messages, name='student_show_messages'),
    path('instructor_create_chat/', views.instructor_create_chat, name='instructor_create_chat'),
    path('instructor_show_messages/', views.instructor_show_messages, name='instructor_show_messages'),
    path('chat_detail/', views.chat_detail, name='chat_detail'),
    path('send_message/', views.send_message, name='send_message'),
    path('instructor_home/', views.instructor_home, name='instructor_home'),
    path('instructor_project_detail/', views.instructor_project_detail, name='instructor_project_detail'),
    path('instructor_new_project/', views.instructor_new_project, name='instructor_new_project'),
    path('instructor_project_create/', views.instructor_project_create, name='instructor_project_create'),
    path('instructor_project_change/', views.instructor_project_change, name='instructor_project_change'),
    path('change_password/', views.change_password, name='change_password'),
    path('instructor_project_edit/', views.instructor_project_edit, name='instructor_project_edit'),  
    path('instructor_project_delete/', views.instructor_project_delete, name='instructor_project_delete'),
    path('instructor_project_close/', views.instructor_project_close, name='instructor_project_close'),
    path('instructor_project_edit/', views.instructor_project_edit, name='instructor_project_edit'),
    path('instructor_allocated_projects/', views.instructor_allocated_projects, name='instructor_allocated_projects'),
    path('logout/', views.logout, name='logout'),
    path('results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Students(models.Model):
	StudentID = models.CharField(max_length=10,default='')
	Name = models.CharField(max_length=30)
	Password = models.CharField(max_length=20)
	CPI = models.FloatField(default=0.00)
	# ResumeLink = models.LinkColumn('item_edit', text='Edit', args=[A('pk')], orderable=False, empty_values=())
	Interests = models.CharField(max_length=40,default='')
	Branch = models.CharField(max_length=20,default='')

class StudentPic(models.Model):
	docfile = models.FileField(upload_to='documents/%Y/%m/%d')
	StudentID = models.CharField(max_length=10,default='')

class InstructorPic(models.Model):
	docfile = models.FileField(upload_to='documents/%Y/%m/%d')
	InstructorID = models.CharField(max_length=10,default='')

		
class Document(models.Model):
	docfile = models.FileField(upload_to='documents/%Y/%m/%d')
	StudentID = models.CharField(max_length=10,default='')

class InstDoc(models.Model):
	docfile = models.FileField(upload_to='documents/%Y/%m/%d')
	InstructorID = models.CharField(max_length=10,default='')

class Instructors(models.Model):
	InstructorID = models.CharField(max_length=10,default='')
	Name = models.CharField(max_length=30,default='')
	Password = models.CharField(max_length=20,default='')
	Branch = models.CharField(max_length=20,default='')
	research = models.CharField(max_length=40,default='')

class AllProjects(models.Model):
	InstructorID = models.ForeignKey(Instructors,on_delete=models.CASCADE)
	ProjectID = models.IntegerField(default=0)
	title = models.CharField(max_length=20,default='')
	description = models.CharField(max_length=200,default='')
	CPIcutoff = models.FloatField(default=0.0)
	max_no_of_students = models.IntegerField(default=0)
	project_status = models.IntegerField(default=1)
	tag = models.CharField(max_length=50,default='')

class AppliedProject(models.Model):
	StudentID = models.ForeignKey(Students,on_delete=models.CASCADE)
	project = models.ForeignKey(AllProjects,on_delete=models.CASCADE)
	time = models.DateTimeField(default=timezone.now)
	allocated = models.IntegerField(default=0)
	accept = models.IntegerField(default=0)

class Chats(models.Model):
	StudentID = models.ForeignKey(Students,on_delete=models.CASCADE)
	InstructorID = models.ForeignKey(Instructors,on_delete=models.CASCADE)

class Message(models.Model):
	MessageID = models.ForeignKey(Chats,on_delete=models.CASCADE)
	SenderID = models.CharField(max_length=10,default='')
	message = models.CharField(max_length=200,default='')
	timestamp = models.DateTimeField(default=timezone.now)

polls/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

polls/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.forms.models import model_to_dict
from django.utils import timezone
from django.db.models import Max
from .models import Students
from .models import Instructors
from .models import AllProjects
from .models import AppliedProject
from .models import Message
from .models import Chats
from django.template import RequestContext
from django.urls import reverse
from .models import Document
from .models import InstDoc
from .models import StudentPic
from .models import InstructorPic
from .forms import DocumentForm

def login(request):

	if request.session.get('stud') != None:
		return redirect('polls:student_home')
	elif request.session.get('inst') != None:
		return redirect('polls:instructor_home')

	if request.method == "POST":

		# if request.POST["type"] == "login":
		userid = request.POST["userid"]
		password = request.POST["password"]

		if Students.objects.filter(StudentID = userid, Password = password).count() > 0:
			# Valid Login/Password
			user = Students.objects.get(StudentID = userid)
			request.session['stud'] = user.StudentID
			return redirect('polls:student_home')
		elif Instructors.objects.filter(InstructorID = userid, Password = password).count() > 0:
			user = Instructors.objects.get(InstructorID = userid)
			request.session['inst'] = user.InstructorID
			return redirect('polls:instructor_home')
		else:
			return render(request, 'polls/login.html')
	else:
		return render(request, 'polls/login.html')

def student_home(request):
	if request.session.get('stud') != None:

		student_id = request.session['stud']
		student1 = Students.objects.get(StudentID=student_id)
		student = model_to_dict(student1)
		# print(student_cpi)
		
		project_list = AllProjects.objects.filter(CPIcutoff__lte = student['CPI'], project_status=1)
		for project in project_list:
			print(project)
		print(student['CPI'])
		applied_projects = AppliedProject.objects.values_list('project',flat=True).filter(StudentID__StudentID=student_id,project__project_status=1)
		# applied_projects = model_to_dict(applied_projects)
		project2=[]
		for i in applied_projects:
			temp_proj = AllProjects.objects.get(pk=i)
			project2.append(temp_proj)
		print(project2)
		project_list = set(project_list).difference(set(project2))
		applied_projects = AppliedProject.objects.values_list('project',flat=True).filter(StudentID__StudentID=student_id,project__project_status=1,allocated=0)
		# applied_projects = model_to_dict(applied_projects)
		project2=[]
		for i in applied_projects:
			temp_proj = AllProjects.objects.get(pk=i)
			project2.append(temp_proj)
		# resume_list = Resume.objects.filter(user = user).order_by("-timestamp")
		# if request.session.get('resume_id') != None:
		# 	del request.session['resume_id']
		# request_list = Request.objects.filter(user_receiver = user)
		# notifications = Notification.objects.filter(user_receiver = user)

		return render(request, 'polls/student_home.html', {'project_list':project_list,'project2':project2,'change_pass':0})
	else:
		return redirect('polls:login')



def student_project_detail(request):
	if request.method == "POST":
		project_id = request.POST["projectid"]
		instructor_id = request.POST["instructorid"]
		project = AllProjects.objects.get(ProjectID=project_id, InstructorID__InstructorID=instructor_id)
		# print(model_to_dict(project))
		return render(request, 'polls/student_project_detail.html',{'project':project})
	else:
		return redirect('polls:student_home')

def student_project_apply(request):
	if request.method == "POST":
		project_id = request.POST["projectid"]
		instructor_id = request.POST["instructorid"]
		student_id = request.session['stud']
		student = Students.objects.get(StudentID=student_id)
		project = AllProjects.objects.get(ProjectID=project_id, InstructorID__InstructorID=instructor_id)
		project2 = AppliedProject(StudentID=student,project=project,time=timezone.now())
		project2.save()
		# request.session["applied"] = 1
		# print(model_to_dict(project))
	return redirect('polls:student_home')

def student_project_cancel(request):
	if request.method == "POST":
		project_id = request.POST["projectid"]
		instructor_id = request.POST["instructorid"]
		student_id = request.session['stud']
		student = Students.objects.get(StudentID=student_id)
		project = AllProjects.objects.get(ProjectID=project_id, InstructorID__InstructorID=instructor_id)
		AppliedProject.objects.get(StudentID=student,project=project).delete()
		# project2.save()
		# request.session["applied"] = 1
		# print(model_to_dict(project))
	return redirect('polls:student_home')

def student_allocated_projects(request):
	if request.session.get('stud') != None:
		student_id = request.session['stud']

		Allocated_projects_pending = AppliedProject.objects.filter(StudentID__StudentID = student_id, allocated = 1, accept = 0,project__project_status=1)
		Allocated_projects_accepted = AppliedProject.objects.filter(StudentID__StudentID = student_id, allocated = 1, accept = 1)
		return render(request, 'polls/student_allocated_projects.html', {'Allocated_projects_pending':Allocated_projects_pending, 'Allocated_projects_accepted':Allocated_projects_accepted})
	else:
		return redirect('polls:student_home')

def student_project_accept(request):
	if request.method == "POST":
		student_id = request.session['stud']
		project_id = request.POST["projectid"]
		instructor_id = request.POST["instructorid"]
		print(student_id)
		print(project_id)
		print(instructor_id)
		AppliedProject.objects.filter(StudentID__StudentID = student_id, project__ProjectID = project_id, project__InstructorID__InstructorID = instructor_id).update(accept = 1)
		# project2.save()
		# print(project2)
		return redirect('polls:student_allocated_projects')
	else:
		return redirect('polls:student_allocated_projects')

def student_project_reject(request):
	if request.method == "POST":
		student_id = request.session['stud']
		project_id = request.POST["projectid"]
		instructor_id = request.POST["instructorid"]
		AppliedProject.objects.filter(StudentID__StudentID = student_id, project__ProjectID = project_id, project__InstructorID__InstructorID = instructor_id).delete()
		return redirect('polls:student_allocated_projects')
	else:
		return redirect('polls:student_allocated_projects')

def student_filter_project(request):
	if request.method == "POST":
		filter_tag = request.POST["filter_tag"]
		student_id = request.session['stud']
		student1 = Students.objects.get(StudentID=student_id)
		student = model_to_dict(student1)
		# print(student_cpi)
		
		project_list = AllProjects.objects.filter(CPIcutoff__lte = student['CPI'], project_status=1,tag__contains=filter_tag)
		applied_projects = AppliedProject.objects.values_list('project',flat=True).filter(StudentID__StudentID=student_id,project__project_status=1)
		# applied_projects = model_to_dict(applied_projects)
		project2=[]
		for i in applied_projects:
			temp_proj = AllProjects.objects.get(pk=i)
			project2.append(temp_proj)
		print(project2)
		project_list = set(project_list).difference(set(project2))
		applied_projects = AppliedProject.objects.values_list('project',flat=True).filter(StudentID__StudentID=student_id,project__project_status=1,accept=0,project__tag__contains=filter_tag)
		# applied_projects = model_to_dict(applied_projects)
		project2=[]
		for i in applied_projects:
			temp_proj = AllProjects.objects.get(pk=i)
			project2.append(temp_proj)
		# resume_list = Resume.objects.filter(user = user).order_by("-timestamp")
		# if request.session.get('resume_id') != None:
		# 	del request.session['resume_id']
		# request_list = Request.objects.filter(user_receiver = user)
		# notifications = Notification.objects.filter(user_receiver = user)

		return render(request, 'polls/student_home.html', {'project_list':project_list,'project2':project2})
	else:
		return redirect('polls:login')

def student_create_chat(request):
	if request.method == "POST":
		student_id = request.session['stud']
		#project_id = request.POST["projectid"]
		instructor_id = request.POST["instructorid"]
		# inst_name = request.POST["instructorid"]
		student = Students.objects.get(StudentID=student_id)
		instructor = Instructors.objects.filter(InstructorID=instructor_id)
		instructor2 = Instructors.objects.filter(Name=instructor_id)
		# already_chat = []
		if instructor:
			instructor = Instructors.objects.get(InstructorID=instructor_id)
			already_chat = Chats.objects.filter(StudentID=student,InstructorID=instructor)
			if not already_chat:
				chat = Chats(StudentID=student,InstructorID=instructor)
				print("hey",chat)
				chat.save()
		elif instructor2:
			instructor2 = Instructors.objects.get(Name=instructor_id)
			if not already_chat:
				chat = Chats(StudentID=student,InstructorID=instructor2)
				print("hey",chat)
				chat.save()
			already_chat2 = Chats.objects.filter(StudentID=student,InstructorID=instructor)
		# print(already_chat)
		# already_chat2 = Chats.objects.filter(StudentID=student,InstructorID=instructor2)
		# print(already_chat)
	return redirect('polls:student_home')

def instructor_create_chat(request):
	if request.method == "POST":
		instructor_id = request.session['inst']
		#project_id = request.POST["projectid"]
		student_id = request.POST["studentid"]
		# stud_name = request.POST["studentid"]
		instructor = Instructors.objects.get(InstructorID=instructor_id)
		student = Students.objects.filter(StudentID=student_id)
		student2 = Students.objects.filter(Name=student_id)
		already_chat = []
		if student:
			student = Students.objects.get(StudentID=student_id)
			already_chat = Chats.objects.filter(StudentID=student,InstructorID=instructor)
			if not already_chat:
				chat = Chats(StudentID=student,InstructorID=instructor)
				print("hey",chat)
				chat.save()
		elif student2:
			student2 = Students.objects.get(Name=student_id)

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/instructor_add_project.html
<form action={% url 'polls:login' %} method="post">
	{% csrf_token %}
    {{ form }}
    <label for="UserID">UserID: </label>
    <input id="UserID" type="text" name="userid">
    <input id="password" type="text" name="password">
    <input type="submit" value="Login">
</form>

polls/templates/polls/instructor_home.html
<html>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
        body {
          background-color: #436145;
        }
        body * {
          box-sizing: border-box;
        }
        
        .header {
          background-color: #327a81;
          color: white;
          font-size: 1.5em;
          padding: 1rem;
          text-align: center;
          text-transform: uppercase;
        }
        div.myclass {
          color: black;
          display: none;
        }
        p.show {
          /*background-color: #eee;*/
          color: black;
          cursor: pointer;
          padding: 18px;
          width: 100%;
          border: none;
          text-align: left;
          outline: none;
          font-size: 15px;
          transition: 0.1s;
        }

        img {
          border-radius: 50%;
          height: 60px;
          width: 60px;
        }
        
        .table-users {
          border: 1px solid #327a81;
          border-radius: 10px;
          box-shadow: 3px 3px 0 rgba(0, 0, 0, 0.1);
          max-width: calc(100% - 2em);
          margin: 1em auto;
          overflow: hidden;
          width: 800px;
        }
        
        table {
          width: 100%;
        }

        table tr:hover {background-color: #D5D8DC !important;}
        table td, table th {
          color: #2b686e;
          padding: 10px;
        }
        table td {
          text-align: center;
          vertical-align: middle;
        }
        table td:last-child {
          font-size: 0.95em;
          line-height: 1.4;
          text-align: left;
        }
        table th {
          text-align: center;
          background-color: #daeff1;
          font-weight: 300;
        }
        table tr:nth-child(2n) {
          background-color: white;
        }
        table tr:nth-child(2n+1) {
          background-color: #edf7f8;
        }
        
        @media screen and (max-width: 700px) {
          table, tr, td {
            display: block;
          }
        
          td:first-child {
            position: absolute;
            top: 50%;
            -webkit-transform: translateY(-50%);
                    transform: translateY(-50%);
            width: 100px;
          }
          td:not(:first-child) {
            clear: both;
            margin-left: 100px;
            padding: 4px 20px 4px 90px;
            position: relative;
            text-align: left;
          }
          td:not(:first-child):before {
            color: #91ced4;
            content: '';
            display: block;
            left: 0;
            position: absolute;
          }
          td:nth-child(2):before {
            content: 'Name:';
          }
          td:nth-child(3):before {
            content: 'Email:';
          }
          td:nth-child(4):before {
            content: 'Phone:';
          }
          td:nth-child(5):before {
            content: 'Comments:';
          }
        
          tr {
            padding: 10px 0;
            position: relative;
          }
          tr:first-child {
            display: none;
          }
        }
        @media screen and (max-width: 500px) {
          .header {
            background-color: transparent;
            color: white;
            font-size: 2em;
            font-weight: 700;
            padding: 0;
            text-shadow: 2px 2px 0 rgba(0, 0, 0, 0.1);
          }
        
          img {
            border: 3px solid;
            border-color: #daeff1;
            height: 100px;
            margin: 0.5rem 0;
            width: 100px;
          }
        
          td:first-child {
            background-color: #c8e7ea;
            border-bottom: 1px solid #91ced4;
            border-radius: 10px 10px 0 0;
            position: relative;
            top: 0;
            -webkit-transform: translateY(0);
                    transform: translateY(0);
            width: 100%;
          }
          td:not(:first-child) {
            margin: 0;
            padding: 5px 1em;
            width: 100%;
          }
          td:not(:first-child):before {
            font-size: .8em;
            padding-top: 0.3em;
            position: relative;
          }
          td:last-child {
            padding-bottom: 1rem !important;
          }
        
          tr {
            background-color: white !important;
            border: 1px solid #6cbec6;
            border-radius: 10px;
            box-shadow: 2px 2px 0 rgba(0, 0, 0, 0.1);
            margin: 0.5rem 0;
            padding: 0;
          }
        
          .table-users {
            border: none;
            box-shadow: none;
            overflow: visible;
          }
        }
        .logoutLblPos{

          position:fixed;
          right:10px;
          top:5px;
        }
        .button2 {background-color: #daeff1;}
        .btn {
          height: 40px;
        }

        .viewprof{

        position:fixed;
        right:100px;
        top:5px;
        }
        .msgpos{
          position:fixed;
          right:230px;
          top:5px;
        }
        </style>
<div style="width:400px;">
    <div style="float: left; width: 130px"> 
      <form action={% url 'polls:instructor_new_project' %} method="post">
      {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label> -->
        <input name="instructorid" type="hidden" value={{instructor_id}}>
        <button class="btn btn-default btn-sm button2">Add project<i class="w3-margin-left fa fa-plus"></i></button>
      </form>
    </div>
    <div style="float: right; width: 225px"> 
        <form action={% url 'polls:login' %} method="post">
    {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label>
      <input id="UserID" type="text" name="userid">
      <input id="password" type="text" name="password"> -->
      <button class="btn btn-default btn-sm button2"><i class="w3-margin-middle fa fa-home"></i></button>
</form>
    </div>
  </div>
<div style="float: middle" class="table-users">
    <div class="header">Users</div>
 
  <table cellspacing="0">
  <tr>
    <th>Title</th>
    <th>Details</th>
    <th>Edit</th>
    <th>Delete Project</th>
    <th>Close Project</th>
  </tr>
  {% for projects in project_list %}
    <tr>
      <td>{{projects.title}}</td>
      <td>
        <form action={% url 'polls:instructor_project_detail' %} method="post">{% csrf_token %}{{ form }}
          <input type="hidden" name="status" value='0'>
          <input type="hidden" name="projectid" value={{projects.ProjectID}}>
          <input type="submit" value="Details">
        </form>
      </td>
      <td>
        <form action={% url 'polls:instructor_project_edit' %} method="post">{% csrf_token %}{{ form }}
          <input type="hidden" name="projectid" value={{projects.ProjectID}}>
          <input type="hidden" name="instructorid" value={{projects.InstructorID.InstructorID}}>
          <input type="submit" value="Edit">
        </form>
      </td>
      <td>
        <form action={% url 'polls:instructor_project_delete' %} method="post">{% csrf_token %}{{ form }}
          <input type="hidden" name="projectid" value={{projects.ProjectID}}>
          <input type="hidden" name="instructorid" value={{projects.InstructorID.InstructorID}}>
          <input type="submit" value="Delete">
        </form>
      </td>
      <td>
        <form action={% url 'polls:instructor_project_close' %} method="post">{% csrf_token %}{{ form }}
          <input type="hidden" name="projectid" value={{projects.ProjectID}}>
          <input type="hidden" name="instructorid" value={{projects.InstructorID.InstructorID}}>
          <input type="submit" value="Close">
        </form>
      </td>
    </tr>
  {% endfor %}

</table>
</div>
<form action={% url 'polls:logout' %} method="post">
    {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label>
      <input id="UserID" type="text" name="userid">
      <input id="password" type="text" name="password"> -->
      <label class="logoutLblPos">
      <button class="btn btn-default btn-sm button2">
          <span class="glyphicon glyphicon-log-out"></span> Log out
      </button>
      </label>
</form>
<form action={% url 'polls:instructor_allocated_projects' %} method="post">
    {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label>
      <input id="UserID" type="text" name="userid">
      <input id="password" type="text" name="password"> -->
      <!-- <input type="submit" value="Closed Projects"> -->
      <button class="btn btn-default btn-sm button2">
        <span class="glyphicon glyphicon-th-list"></span> Closed Projects
    </button>

</form>

<form action={% url 'polls:instructor_show_messages' %} method="post">
    {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label>
      <input id="UserID" type="text" name="userid">
      <input id="password" type="text" name="password"> -->
      <label class="msgpos">
      <!-- <input type="submit" value="Messages"> -->
      <button class="btn btn-default btn-sm button2">
          <span class="glyphicon glyphicon-envelope"></span> Messages
      </button>

    </label>
</form>
<form action={% url 'polls:instructor_create_chat' %} method="post">
    {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label> -->
      <input id="studentid" type="text" name="studentid">
      <!-- <input id="password" type="text" name="password"> -->
      <!-- <input type="submit" value="Create Chat"> -->
      <button class="btn btn-default btn-sm button2">
        <span class="glyphicon glyphicon-pencil"></span> Create Chat
    </button>

</form>
<p class="show" onclick="myFunction()"><b>Click to change password</b></p>
<div id="mydiv" class="myclass">
  <form action={% url 'polls:change_password' %} method="post">
    {% csrf_token %}
      {{ form }}
      <label for="oldpass">Enter Old Password: </label>
      <input id="oldpass" type="password" name="oldpass">
      <label for="newpass">Enter New Password: </label>
      <input id="newpass" type="password" name="newpass">
      <label for="newpassagain">Enter New Password again: </label>
      <input id="newpassagain" type="password" name="newpassagain">
      <input type="submit" value="Change Password">
</form>
{% if change_pass == 1 %}
password changed succesfully
{% elif change_pass == 2 %}
Password entered is incorrect
{% endif %}
</p>
</div>
<form action={% url 'polls:instructor_edit_profile' %} method="post">
  {% csrf_token %}
    {{ form }}
    
    <!-- <input type="submit" value="View Profile"> -->
    <!-- <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button> -->
    <label class="viewprof">
    <button class="btn btn-default btn-sm button2">View Profile<i class="w3-margin-left fa fa-user"></i></button>
</label>
</form>

<script>
  function myFunction() {
    var x = document.getElementById("mydiv");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>
</html>

polls/templates/polls/student_instructor_chat.html
<table>
  <tr>
    <th>Title</th>
    <th>Project Title</th>
    <th>Details</th>
    <th></th>
  </tr>
  {% for chats in messages %}
    <tr>
      <td>{{chats.SenderID}}</td>
      <td>{{chats.ReceiverID}}</td>
      <td>{{chats.StudentID}}</td>
      <td>{{chats.InstructorD}}</td>
    </tr>
  {% endfor %}
</table>

<form action={% url 'polls:student_new_message' %} method="post">
    {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label> -->
      <input id="message" type="text" name="message">
      <input name="instructorid" type="hidden" value={{instructor_id}}>
      <!--<input name="timestamp" type="hidden" value={{instructor_id}}>-->
      <input type="Submit" value="Send">
</form>

<form action={% url 'polls:logout' %} method="post">
    {% csrf_token %}
      {{ form }}
      <!-- <label for="UserID">UserID: </label>
      <input id="UserID" type="text" name="userid">
      <input id="password" type="text" name="password"> -->
      <input type="submit" value="logout">
</form>